
package Car;

import ConexionBD.Conexion;

import java.awt.Cursor;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;

import java.util.ArrayList;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vacio
 */
public class Autos extends javax.swing.JPanel {
    
    Conexion conectar = new Conexion();
    Connection conect;
    Principal princ;
    DefaultTableModel modelo;
    ResultSetMetaData metaData;
    Statement st;
    ResultSet rs;
    int clienteID = 0;
    
    /** Creates new form Autos */
    public Autos(Principal principal) {
        initComponents();
        this.princ = principal;
        /* consultar(clientID); */
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jScrollPane1 = new javax.swing.JScrollPane();
        TblAutos = new javax.swing.JTable();

        setName(""); // NOI18N

        TblAutos = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col){
                for(int i = 0; i<TblAutos.getRowCount(); i++){
                    if(row==i){
                        return false;
                    }
                }
                return true;
            }
        };
        TblAutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TblAutos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                TblAutosMouseMoved(evt);
            }
        });
        TblAutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblAutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblAutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }//GEN-END:initComponents

    private void TblAutosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblAutosMouseMoved
    if(TblAutos.columnAtPoint(evt.getPoint())==6)
    {
        TblAutos.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
    }
    else
    {
        TblAutos.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }
    }//GEN-LAST:event_TblAutosMouseMoved

    private void TblAutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblAutosMouseClicked
    int row = TblAutos.getSelectedRow();
    int columnNumber = TblAutos.getSelectedColumn();
    int clienteID = (Integer)TblAutos.getValueAt(row, 0);
    String placas = (String)TblAutos.getValueAt(row,1);
       if(evt.getClickCount() == 1 && columnNumber == 6){
           FrmAccesorios acce = new FrmAccesorios(clienteID);
           acce.setVisible(true);
           acce.ConsultaAccesorios(placas);
           acce.Placas = placas;
       }
    }//GEN-LAST:event_TblAutosMouseClicked
    
    public void consultar(int clientID){
        this.clienteID = clientID;
        String sql = "select * from automovil where idCliente = "+clientID;
        try{
            conect = conectar.getConnection();
            st = conect.createStatement();
            rs = st.executeQuery(sql);
            
            Object[] autos = new Object[7];
            metaData = rs.getMetaData();
            TblAutos.setDefaultRenderer(Object.class, new ImgTabla());
            modelo = (DefaultTableModel)TblAutos.getModel();
            
            int cols = metaData.getColumnCount()+1;
            String[] colName = new String[cols];
            for(int i=0; i<cols; i++){
                if(i == 6){
                    colName[6] = "Accesorios";
                    modelo.setColumnIdentifiers(colName);
                } else {
                    colName[i] = metaData.getColumnName(i + 1);
                    modelo.setColumnIdentifiers(colName);
                }
            }
            while(rs.next()){
                autos[0] = rs.getInt(1);
                autos[1] = rs.getString(2);
                autos[2] = rs.getString(3);
                autos[3] = rs.getString(4);
                autos[4] = rs.getString(5);
                autos[5] = rs.getString(6);
                autos[6] = new JLabel(new ImageIcon(getClass().getResource("/resources/add2_16001158.png")));
                modelo.addRow(autos);
            }
            this.princ.jlBack.setVisible(true);
            /* st.close();
            conect.close(); */
        }catch(Exception e){
            System.out.println("Ocurrio un error: "+e);
        }
    }
    
    public List buscarAuto(String filter, String valorBusqueda){
        List<Integer> idCliente = new ArrayList<Integer>();
        String sql = "";
        
        if(!filter.equals("IdCliente")){
            sql = "SELECT * FROM automovil WHERE Placas like '%"+valorBusqueda+"%'";
            
        }else{
            sql = "select * from automovil where idCliente = "+valorBusqueda;
        }
        try{
            conect = conectar.getConnection();
            st = conect.createStatement();
            rs = st.executeQuery(sql);
            
            Object[] autos = new Object[7];
            metaData = rs.getMetaData();
            TblAutos.setDefaultRenderer(Object.class, new ImgTabla());
            modelo = (DefaultTableModel)TblAutos.getModel();
            
            int cols = metaData.getColumnCount()+1;
            String[] colName = new String[cols];
            for(int i=0; i<cols; i++){
                if(i == 6){
                    colName[6] = "Accesorios";
                    modelo.setColumnIdentifiers(colName);
                } else {
                    colName[i] = metaData.getColumnName(i + 1);
                    modelo.setColumnIdentifiers(colName);
                }
            }
            while(rs.next()){
                autos[0] = rs.getInt(1);
                autos[1] = rs.getString(2);
                autos[2] = rs.getString(3);
                autos[3] = rs.getString(4);
                autos[4] = rs.getString(5);
                autos[5] = rs.getString(6);
                autos[6] = new JLabel(new ImageIcon(getClass().getResource("/resources/add2_16001158.png")));
                modelo.addRow(autos);
                idCliente.add(rs.getInt(1));
            }
            this.princ.jLAddAutos.setVisible(true);
            this.princ.jlBack.setVisible(true);
            return idCliente;
            /* st.close();
            conect.close(); */
        }catch(Exception e){
            System.out.println("Ocurrio un error: "+e);
        }
        return idCliente;
}
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblAutos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
