
package Car;

import ConexionBD.Conexion;

import java.awt.Image;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author vacio
 */
public class FrmAccesorios extends javax.swing.JFrame {
    Conexion conn = new Conexion();
    Connection conect;
    Statement st;
    String Placas;
    int idCliente;
    int countRow = 0;
    
    /** Creates new form FrmAccesorios */
    public FrmAccesorios(int idCliente) {
        initComponents();
        this.idCliente = idCliente;
        Image icon = new ImageIcon(getClass().getResource("/resources/CabrioletRed-4.png")).getImage();
        setIconImage(icon);
        /* ConsultaAccesorios(2); */
        txtPlacas.setText(Placas);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPlacas = new javax.swing.JTextField();
        chkEstereo = new javax.swing.JCheckBox();
        chkBaston = new javax.swing.JCheckBox();
        chkLlave = new javax.swing.JCheckBox();
        chkGato = new javax.swing.JCheckBox();
        chkLlanta = new javax.swing.JCheckBox();
        chkCaja = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOtros = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CarRegister");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Accesorios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Placas");

        txtPlacas.setEditable(false);
        txtPlacas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtPlacas.setEnabled(false);

        chkEstereo.setText("Estereo");

        chkBaston.setText("Bastón de seguridad");

        chkLlave.setText("Llave de cruz");

        chkGato.setText("Gato");

        chkLlanta.setText("Llanta de refaccion");

        chkCaja.setText("Caja de Herramientas");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Otros:");

        txtOtros.setColumns(20);
        txtOtros.setRows(5);
        jScrollPane1.setViewportView(txtOtros);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkLlave)
                                    .addComponent(chkGato)
                                    .addComponent(chkLlanta)
                                    .addComponent(chkCaja)
                                    .addComponent(chkEstereo)
                                    .addComponent(chkBaston)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkEstereo)
                .addGap(2, 2, 2)
                .addComponent(chkBaston)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkLlave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkGato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkLlanta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkCaja)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int valorEstereo = 0, valorBaston = 0, valorLlave = 0, valorGato = 0, valorllanta = 0, valorCaja = 0;   
        String valorTxtOtros = "", valorTxtPlacas = "";
        
        if(chkEstereo.isSelected()){
            valorEstereo = 1;
        }
        if(chkBaston.isSelected()){
            valorBaston = 1;
        }
        if(chkLlave.isSelected()){
            valorLlave = 1;
            
        }
        if(chkGato.isSelected()){
            valorGato = 1;
        }
        if(chkLlanta.isSelected()){
            valorllanta = 1;
        }
        if(chkCaja.isSelected()){
            valorCaja = 1;
        }
        
        if(txtOtros.getText() != null || txtOtros.getText() != ""){
            valorTxtOtros = txtOtros.getText();
        }
        
        if(txtPlacas.getText() != null || txtPlacas.getText() != ""){
            valorTxtPlacas = txtPlacas.getText();
        }
        if(this.countRow > 0){
            UpdateAccesorios(valorTxtPlacas,this.idCliente,valorEstereo,valorBaston,valorLlave,valorGato,valorllanta,
                               valorCaja,valorTxtOtros);
        }else{
            insertAccesorios(valorTxtPlacas,this.idCliente,valorEstereo,valorBaston,valorLlave,valorGato,valorllanta,
                               valorCaja,valorTxtOtros);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(FrmAccesorios.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(FrmAccesorios.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(FrmAccesorios.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(FrmAccesorios.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new FrmAccesorios(0).setVisible(true);
                }
            });
    }
    
    public void ConsultaAccesorios(String placas){
    
        String query = "Select * from accesorios where Placas = '"+placas+"'";
        
        try {
            conect = conn.getConnection();
            st = conect.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()){
                txtPlacas.setText(rs.getString(1));
                if(rs.getInt(3) == 1){
                    chkEstereo.setSelected(true);
                }else{
                    chkEstereo.setSelected(false);
                }
                if(rs.getInt(4) == 1){
                    chkLlave.setSelected(true);
                }else{
                    chkLlave.setSelected(false);
                }
                if(rs.getInt(5) == 1){
                    chkGato.setSelected(true);
                }else{
                    chkGato.setSelected(false);
                }
                if(rs.getInt(6) == 1){
                    chkLlanta.setSelected(true);
                }else{
                    chkLlanta.setSelected(false);
                }
                if(rs.getInt(7) == 1){
                    chkCaja.setSelected(true);
                }else{
                    chkCaja.setSelected(false);
                }
                if(rs.getInt(8) == 1){
                    chkBaston.setSelected(true);
                }else{
                    chkBaston.setSelected(false);
                }
                if(rs.getString(9) != null){
                    txtOtros.setText(rs.getString(9));
                }
                
            this.countRow++;
            }
            
        } catch(Exception e){
            System.out.println("Ocurrio un error:  "+e);
        }
    }
    
    
    public void  UpdateAccesorios(String Placas,int clienteID, int Estereo, int Baston, int Llave, int Gato, 
                                       int llanta, int Caja, String Otros){
        /* JOptionPane.showMessageDialog(null,"Placas: "+Placas+" clienteID: "+clienteID+" Estereo: "+ Estereo+" Baston: "+Baston+" Llave: "+  Llave+
                           " Gato: "+Gato+" Llanta: "+llanta+" Caja: "+Caja+" Otros: "+Otros); */
        String query = "UPDATE accesorios set Estereo = "+Estereo+",Llave_Cruz = "+Llave+",Gato = "+Gato+",Refaccion = "+llanta+
                        ",Caja_Herramientas = "+Caja+",Baston_Seguridad = "+Baston+",Otros = '"+Otros+"' Where Placas = '"+Placas+
                        "' AND idCliente = "+idCliente+";";
        try{
            conect = conn.getConnection();
            st = conect.createStatement();
   
            st.executeUpdate(query);
            st.close();
            
            JOptionPane.showMessageDialog(this,"Accesorios actualizados");
        }catch(Exception e){
            System.out.println("Error al actualizar accesorios: "+e);
        }
    }
    
    public void insertAccesorios(String Placas,int clienteID, int Estereo, int Baston, int Llave, int Gato, 
                                       int llanta, int Caja, String Otros){
        /* JOptionPane.showMessageDialog(null,"Placas: "+Placas+" clienteID: "+clienteID+" Estereo: "+ Estereo+" Baston: "+Baston+" Llave: "+  Llave+
                           " Gato: "+Gato+" Llanta: "+llanta+" Caja: "+Caja+" Otros: "+Otros); */
        String query = "INSERT INTO accesorios(Placas,idCliente,Estereo,Llave_Cruz,Gato,Refaccion,Caja_Herramientas," +
                                    "Baston_Seguridad,Otros) VALUES('"+Placas+"',"+clienteID+","+Estereo+","+Llave+","+Gato+","+
                                                                    llanta+","+Caja+",'"+Otros+"');";

        try {
            conect = conn.getConnection();
            conect.prepareStatement(query);
            st.executeUpdate(query);
            st.close();
            
            JOptionPane.showMessageDialog(this,"Accesorios registrados");
        }catch(Exception e){
            System.out.println("Error al registrar accesorios: "+e);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkBaston;
    private javax.swing.JCheckBox chkCaja;
    private javax.swing.JCheckBox chkEstereo;
    private javax.swing.JCheckBox chkGato;
    private javax.swing.JCheckBox chkLlanta;
    private javax.swing.JCheckBox chkLlave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtOtros;
    private javax.swing.JTextField txtPlacas;
    // End of variables declaration//GEN-END:variables
    
}
