
package Car;

import ConexionBD.Conexion;

import java.awt.Image;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import java.util.Base64;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author vacio
 */
public class FrmRegistro extends javax.swing.JFrame {
    Connection conectInsertUsuario = Conexion.Conectar();
    Statement stInsertUsuario;
    
    /** Creates new form FrmRegistro */
    public FrmRegistro() {
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/resources/CabrioletRed-4.png")).getImage();
        setIconImage(icon);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel3 = new javax.swing.JPanel();
        jTFUsuario = new javax.swing.JTextField();
        jTCorreo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLPropietario = new javax.swing.JLabel();
        jLApPaterno1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLApMaterno = new javax.swing.JLabel();
        jBGuardar = new javax.swing.JButton();
        jLApMaterno1 = new javax.swing.JLabel();
        jTPassword = new javax.swing.JPasswordField();
        jTConfPassword = new javax.swing.JPasswordField();
        jCBShowContra = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CarRegister");

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setToolTipText("");

        jLPropietario.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLPropietario.setForeground(new java.awt.Color(255, 255, 255));
        jLPropietario.setText("Agregar Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLPropietario)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLApPaterno1.setText("Correo electronico:");

        jLabel1.setText("Usuario: ");

        jLApMaterno.setText("Contraseña:");

        jBGuardar.setText("Guardar");
        jBGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBGuardarMouseClicked(evt);
            }
        });

        jLApMaterno1.setText("Confirmación contraseña:");

        jCBShowContra.setText("Mostrar contraseña");
        jCBShowContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBShowContraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLApMaterno)
                                    .addComponent(jLApPaterno1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLApMaterno1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTPassword)
                                    .addComponent(jTConfPassword)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCBShowContra)
                                            .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApPaterno1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApMaterno1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTConfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBShowContra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }//GEN-END:initComponents

    private void jBGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBGuardarMouseClicked
            String usuario = jTFUsuario.getText();
            String correo = jTCorreo.getText();
            String contrasenia = jTPassword.getText();
            String confContra = jTConfPassword.getText();
        
            if(!usuario.isEmpty()&& !correo.isEmpty() && !contrasenia.isEmpty()){
                
                if(!buscaCorreo(correo)){    
                    if(contrasenia.equals(confContra)){
                        String passwd = Base64.getEncoder().encodeToString(contrasenia.getBytes());
                        insertUsuario(usuario,correo,passwd);
                        
                    }else{
                        JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "El correo ya se encuentra registrado");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Se deben llenar todos los campos");
            }
        
        
    }//GEN-LAST:event_jBGuardarMouseClicked

    private void jCBShowContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBShowContraActionPerformed
        if(jCBShowContra.isSelected()){
            jTPassword.setEchoChar((char)0);
            jTConfPassword.setEchoChar((char)0);
        }else{
            jTPassword.setEchoChar('*');
            jTConfPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jCBShowContraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(FrmRegistro.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(FrmRegistro.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(FrmRegistro.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(FrmRegistro.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new FrmRegistro().setVisible(true);
                }
            });
    }
    
    public Boolean buscaCorreo(String correo){
     Boolean correoExistente = false;
     Statement st;
     ResultSet rs;
     
     String query = "select * from usuarios where correo = '"+correo+"'";
     
        try{

            st = conectInsertUsuario.createStatement();
            rs = st.executeQuery(query);
            
           while(rs.next()){
                correo = rs.getString(3);
               if(!correo.isEmpty()){
                    correoExistente = true;   
                }
            }
            
        }catch(Exception e){
            System.out.println("Ocurrio un error: "+e);
        }
             
     return correoExistente;   
    }
    
    public void insertUsuario(String usuario, String correo, String contraseña){
        
        String query = "INSERT INTO usuarios(usuario, correo, password)" +
            "VALUES('"+usuario+"','"+correo+"','"+contraseña+"');";

        try {
           
            PreparedStatement execQuery = conectInsertUsuario.prepareStatement(query);
            execQuery.executeUpdate();
            
            int resp = JOptionPane.showConfirmDialog(this,"Usuario agregado correctamente",null,JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE);
            System.out.println(resp);
            this.dispose();
               
            } catch(Exception e){
            System.out.println("Error al agregar propietario: "+e);
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JCheckBox jCBShowContra;
    private javax.swing.JLabel jLApMaterno;
    private javax.swing.JLabel jLApMaterno1;
    private javax.swing.JLabel jLApPaterno1;
    private javax.swing.JLabel jLPropietario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jTConfPassword;
    private javax.swing.JTextField jTCorreo;
    private javax.swing.JTextField jTFUsuario;
    private javax.swing.JPasswordField jTPassword;
    // End of variables declaration//GEN-END:variables

}
