
package Car;

import java.awt.Image;

import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;

import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author vacio
 */
public class Principal extends javax.swing.JFrame {
    @SuppressWarnings("compatibility:4250987250289230427")
    private static final long serialVersionUID = 1L;
    Propietarios prop = new Propietarios(this);
    int IdCliente = 0;
    /** Creates new form Principal */
    public Principal() {
        initComponents();
        ShowPanel(1,0);
        Image icon = new ImageIcon(getClass().getResource("/resources/CabrioletRed-4.png")).getImage();
        setIconImage(icon);
        jLAddAutos.setVisible(false);
        jlBack.setVisible(false);
        
        bgBuscarPor.add(rbPropietario);
        bgBuscarPor.add(rbAuto);
        
        bgBusquedas.add(rbNombre);
        bgBusquedas.add(rbApPaterno);
        bgBusquedas.add(rbApMaterno);
        bgBusquedas.add(rbTelefono);
        bgBusquedas.add(rbIdClienteProp);
        bgBusquedas.add(rbPlacas);
        bgBusquedas.add(rbIdClienteAuto);
        
        rbNombre.setVisible(false);
        rbApPaterno.setVisible(false);
        rbApMaterno.setVisible(false);
        rbTelefono.setVisible(false);
        rbIdClienteProp.setVisible(false);
        
        rbPlacas.setVisible(false);
        rbIdClienteAuto.setVisible(false);
        
        tApMaterno.setVisible(false);
        tApPaterno.setVisible(false);
        tIdClienteAuto.setVisible(false);
        tIdClienteProp.setVisible(false);
        tNombre.setVisible(false);
        tPlacas.setVisible(false);
        tTelefono.setVisible(false);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        bgBusquedas = new javax.swing.ButtonGroup();
        bgBuscarPor = new javax.swing.ButtonGroup();
        Background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        rbPropietario = new javax.swing.JRadioButton();
        rbAuto = new javax.swing.JRadioButton();
        rbNombre = new javax.swing.JRadioButton();
        rbApPaterno = new javax.swing.JRadioButton();
        rbApMaterno = new javax.swing.JRadioButton();
        rbTelefono = new javax.swing.JRadioButton();
        tNombre = new javax.swing.JTextField();
        tApPaterno = new javax.swing.JTextField();
        tApMaterno = new javax.swing.JTextField();
        tTelefono = new javax.swing.JTextField();
        rbPlacas = new javax.swing.JRadioButton();
        tPlacas = new javax.swing.JTextField();
        rbIdClienteAuto = new javax.swing.JRadioButton();
        tIdClienteAuto = new javax.swing.JTextField();
        rbIdClienteProp = new javax.swing.JRadioButton();
        tIdClienteProp = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jlBack = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLAddPropietarios = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPTablas = new javax.swing.JPanel();
        jPTablas2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLAddAutos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CarRegister");
        setIconImage(getIconImage());

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setPreferredSize(new java.awt.Dimension(1060, 585));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CarRegister v2.0");
        jLabel2.setFocusable(false);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buscar por:");

        rbPropietario.setForeground(new java.awt.Color(255, 255, 255));
        rbPropietario.setText("Propietario");
        rbPropietario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbPropietarioItemStateChanged(evt);
            }
        });

        rbAuto.setForeground(new java.awt.Color(255, 255, 255));
        rbAuto.setText("Auto");
        rbAuto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbAutoItemStateChanged(evt);
            }
        });

        rbNombre.setForeground(new java.awt.Color(255, 255, 255));
        rbNombre.setText("Nombre");
        rbNombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbNombreItemStateChanged(evt);
            }
        });

        rbApPaterno.setForeground(new java.awt.Color(255, 255, 255));
        rbApPaterno.setText("Apellido Paterno");
        rbApPaterno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbApPaternoItemStateChanged(evt);
            }
        });

        rbApMaterno.setForeground(new java.awt.Color(255, 255, 255));
        rbApMaterno.setText("Apellido Materno");
        rbApMaterno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbApMaternoItemStateChanged(evt);
            }
        });

        rbTelefono.setForeground(new java.awt.Color(255, 255, 255));
        rbTelefono.setText("Telefono");
        rbTelefono.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbTelefonoItemStateChanged(evt);
            }
        });

        rbPlacas.setForeground(new java.awt.Color(255, 255, 255));
        rbPlacas.setText("Placas");
        rbPlacas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbPlacasItemStateChanged(evt);
            }
        });

        rbIdClienteAuto.setForeground(new java.awt.Color(255, 255, 255));
        rbIdClienteAuto.setText("ID cliente");
        rbIdClienteAuto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbIdClienteAutoItemStateChanged(evt);
            }
        });

        rbIdClienteProp.setForeground(new java.awt.Color(255, 255, 255));
        rbIdClienteProp.setText("ID cliente");
        rbIdClienteProp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbIdClientePropItemStateChanged(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        jlBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/left-28.png"))); // NOI18N
        jlBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbAuto)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbPlacas)
                            .addComponent(rbIdClienteAuto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tIdClienteAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbPropietario)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbApPaterno)
                            .addComponent(rbNombre)
                            .addComponent(rbApMaterno)
                            .addComponent(rbTelefono)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbIdClienteProp)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(tIdClienteProp, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlBack, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPropietario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbApPaterno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbApMaterno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbIdClienteProp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tIdClienteProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbAuto)
                .addGap(7, 7, 7)
                .addComponent(rbPlacas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbIdClienteAuto)
                .addGap(9, 9, 9)
                .addComponent(tIdClienteAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jlBack.getAccessibleContext().setAccessibleName("jlBack");

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 688));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Propietarios");

        jLAddPropietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/plus-5-28.png"))); // NOI18N
        jLAddPropietarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLAddPropietarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLAddPropietariosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLAddPropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4))
            .addComponent(jLAddPropietarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 140, 830, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/CarRegister.PNG"))); // NOI18N
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 0, 505, 134));

        javax.swing.GroupLayout jPTablasLayout = new javax.swing.GroupLayout(jPTablas);
        jPTablas.setLayout(jPTablasLayout);
        jPTablasLayout.setHorizontalGroup(
            jPTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPTablasLayout.setVerticalGroup(
            jPTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        Background.add(jPTablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 194, 820, -1));

        javax.swing.GroupLayout jPTablas2Layout = new javax.swing.GroupLayout(jPTablas2);
        jPTablas2.setLayout(jPTablas2Layout);
        jPTablas2Layout.setHorizontalGroup(
            jPTablas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPTablas2Layout.setVerticalGroup(
            jPTablas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        Background.add(jPTablas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 474, 820, -1));

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Auto(s)");

        jLAddAutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/plus-5-28.png"))); // NOI18N
        jLAddAutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLAddAutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLAddAutosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLAddAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLAddAutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Background.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 420, 830, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 1069, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }//GEN-END:initComponents

    private void rbApPaternoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbApPaternoItemStateChanged
        tNombre.setEnabled(false);
        tApPaterno.setEnabled(true);
        tApMaterno.setEnabled(false);
        tTelefono.setEnabled(false);
        tIdClienteProp.setEnabled(false);
        tPlacas.setEnabled(false);
        tIdClienteAuto.setEnabled(false);
        
        tNombre.setText("");
        tApMaterno.setText("");
        tTelefono.setText("");
        tIdClienteProp.setText("");
        tPlacas.setText("");
        tIdClienteAuto.setText("");
    }//GEN-LAST:event_rbApPaternoItemStateChanged

    private void rbApMaternoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbApMaternoItemStateChanged
        tNombre.setEnabled(false);
        tApPaterno.setEnabled(false);
        tApMaterno.setEnabled(true);
        tTelefono.setEnabled(false);
        tIdClienteProp.setEnabled(false);
        tPlacas.setEnabled(false);
        tIdClienteAuto.setEnabled(false);
        
        tNombre.setText("");
        tApPaterno.setText("");
        tTelefono.setText("");
        tIdClienteProp.setText("");
        tPlacas.setText("");
        tIdClienteAuto.setText("");
    }//GEN-LAST:event_rbApMaternoItemStateChanged

    private void rbTelefonoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbTelefonoItemStateChanged
        tNombre.setEnabled(false);
        tApPaterno.setEnabled(false);
        tApMaterno.setEnabled(false);
        tTelefono.setEnabled(true);
        tIdClienteProp.setEnabled(false);
        tPlacas.setEnabled(false);
        tIdClienteAuto.setEnabled(false);
        
        tNombre.setText("");
        tApPaterno.setText("");
        tApMaterno.setText("");
        tIdClienteProp.setText("");
        tPlacas.setText("");
        tIdClienteAuto.setText("");
    }//GEN-LAST:event_rbTelefonoItemStateChanged

    private void rbIdClientePropItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbIdClientePropItemStateChanged
        tNombre.setEnabled(false);
        tApPaterno.setEnabled(false);
        tApMaterno.setEnabled(false);
        tTelefono.setEnabled(false);
        tIdClienteProp.setEnabled(true);
        tPlacas.setEnabled(false);
        tIdClienteAuto.setEnabled(false);
        
        tNombre.setText("");
        tApPaterno.setText("");
        tApMaterno.setText("");
        tTelefono.setText("");
        tPlacas.setText("");
        tIdClienteAuto.setText("");
    }//GEN-LAST:event_rbIdClientePropItemStateChanged

    private void rbPlacasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbPlacasItemStateChanged
        tNombre.setEnabled(false);
        tApPaterno.setEnabled(false);
        tApMaterno.setEnabled(false);
        tTelefono.setEnabled(false);
        tIdClienteProp.setEnabled(false);
        tPlacas.setEnabled(true);
        tIdClienteAuto.setEnabled(false);
        
        tNombre.setText("");
        tApPaterno.setText("");
        tApMaterno.setText("");
        tTelefono.setText("");
        tIdClienteProp.setText("");
        tIdClienteAuto.setText("");
    }//GEN-LAST:event_rbPlacasItemStateChanged

    private void rbIdClienteAutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbIdClienteAutoItemStateChanged
        tNombre.setEnabled(false);
        tApPaterno.setEnabled(false);
        tApMaterno.setEnabled(false);
        tTelefono.setEnabled(false);
        tIdClienteProp.setEnabled(false);
        tPlacas.setEnabled(false);
        tIdClienteAuto.setEnabled(true);
        
        tNombre.setText("");
        tApPaterno.setText("");
        tApMaterno.setText("");
        tTelefono.setText("");
        tIdClienteProp.setText("");
        tPlacas.setText("");
    }//GEN-LAST:event_rbIdClienteAutoItemStateChanged

    private void rbPropietarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbPropietarioItemStateChanged
        if(rbPropietario.isSelected()){
            rbNombre.setVisible(true);
            tNombre.setVisible(true); 
            tNombre.setEnabled(false);
            rbApPaterno.setVisible(true);
            tApPaterno.setVisible(true); 
            tApPaterno.setEnabled(false);
            rbApMaterno.setVisible(true);
            tApMaterno.setVisible(true); 
            tApMaterno.setEnabled(false);
            rbTelefono.setVisible(true);
            tTelefono.setVisible(true); 
            tTelefono.setEnabled(false);
            rbIdClienteProp.setVisible(true);
            tIdClienteProp.setVisible(true); 
            tIdClienteProp.setEnabled(false);
    
            rbPlacas.setVisible(false);
            tPlacas.setVisible(false);
            tPlacas.setEnabled(false);
            rbIdClienteAuto.setVisible(false);
            tIdClienteAuto.setVisible(false);
            tIdClienteAuto.setEnabled(false);
            
        }
    }//GEN-LAST:event_rbPropietarioItemStateChanged

    private void rbAutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbAutoItemStateChanged
        if(rbAuto.isSelected()){
            rbNombre.setVisible(false);
            tNombre.setVisible(false);
            rbApPaterno.setVisible(false);
            tApPaterno.setVisible(false);
            rbApMaterno.setVisible(false);
            tApMaterno.setVisible(false);
            rbTelefono.setVisible(false);
            tTelefono.setVisible(false);
            rbIdClienteProp.setVisible(false);
            tIdClienteProp.setVisible(false);
    
            rbPlacas.setVisible(true);
            tPlacas.setVisible(true);
            rbIdClienteAuto.setVisible(true);
            tIdClienteAuto.setVisible(true);
                    
        }
    }//GEN-LAST:event_rbAutoItemStateChanged

    private void rbNombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbNombreItemStateChanged
        tNombre.setEnabled(true);
        tApPaterno.setEnabled(false);
        tApMaterno.setEnabled(false);
        tTelefono.setEnabled(false);
        tIdClienteProp.setEnabled(false);
        tPlacas.setEnabled(false);
        tIdClienteAuto.setEnabled(false);
        
        tApPaterno.setText("");
        tApMaterno.setText("");
        tTelefono.setText("");
        tIdClienteProp.setText("");
        tPlacas.setText("");
        tIdClienteAuto.setText("");
    }//GEN-LAST:event_rbNombreItemStateChanged

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
    String TextValue = "";
    String filter = "";
    if(!rbPropietario.isSelected() && !rbAuto.isSelected()){
        JOptionPane.showMessageDialog(this, "Debe realizar una selección");
    }else{
        if (rbPropietario.isSelected() && !rbNombre.isSelected() && !rbApPaterno.isSelected() &&
            !rbApMaterno.isSelected() && !rbIdClienteProp.isSelected() && !rbTelefono.isSelected()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una opcion de busqueda");
        }else if(rbAuto.isSelected() && !rbPlacas.isSelected() && !rbIdClienteAuto.isSelected())
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una opcion de busqueda");
        }

    }
    for (Enumeration<AbstractButton> buttons = bgBusquedas.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                switch (button.getText()){
                    case "Nombre":
                        TextValue = tNombre.getText();
                        filter = "Nombre";
                    break;
                    case "Apellido Paterno":
                        TextValue = tApPaterno.getText();
                        filter = "Apellido_Paterno";
                    break;
                    case "Apellido Materno":
                        TextValue = tApMaterno.getText();
                        filter = "Apellido_Materno";
                    break;
                    case "Telefono":
                        TextValue = tTelefono.getText();
                        filter = "Telefono";
                    break;
                    case "ID cliente":
                        filter = "IdCliente";
                        TextValue = tIdClienteProp.getText();
                    if(tIdClienteProp.getText().isEmpty()){
                        TextValue = tIdClienteAuto.getText();
                    }
                    break;
                    case "Placas":
                        filter = "Placas";
                        TextValue = tPlacas.getText();
                    break;
                }
                if (!TextValue.isEmpty()) {
                    for (Enumeration<AbstractButton> busquedas = bgBuscarPor. getElements(); busquedas.hasMoreElements();) {
                            AbstractButton busquedaPor = busquedas.nextElement();
                            if (busquedaPor.isSelected()) {
                                buscar(busquedaPor.getText(),TextValue,filter);
                            }
                        }
                    /* JOptionPane.showMessageDialog(this, TextValue); */
                } else {
                    JOptionPane.showMessageDialog(this, "Ingresa un valor para el campo " + button.getText());
                }
            }
            else{
                switch (button.getText()){
                    case "Nombre":
                        tNombre.setText("");
                    break;
                    case "Apellido Paterno":
                        tApPaterno.setText("");
                    break;
                    case "Apellido Materno":
                        tApMaterno.setText("");
                    break;
                    case "Telefono":
                        tTelefono.setText("");
                    break;
                    case "ID":
                        tIdClienteProp.setText("");
                    break;
                    case "Placas":
                        tPlacas.setText("");
                    break;
                }
            }
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void jlBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBackMouseClicked
        actualizaVista(this);
    }//GEN-LAST:event_jlBackMouseClicked

    private void jLAddPropietariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAddPropietariosMouseClicked
        FrmAgregaPropietarios AddProp = new FrmAgregaPropietarios(this);
        AddProp.setVisible(true);
    }//GEN-LAST:event_jLAddPropietariosMouseClicked

    private void jLAddAutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAddAutosMouseClicked
        FrmAgregaAutos AddAutos = new FrmAgregaAutos(this, IdCliente);
        AddAutos.setVisible(true);
    }//GEN-LAST:event_jLAddAutosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Principal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Principal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Principal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Principal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new Principal().setVisible(true);
                }
            });
    }
    
    public void ShowPanel(int numberPanel, int clientID){
        this.IdCliente = clientID;
        if (numberPanel == 1 && clientID == 0){
            /* Propietarios prop = new Propietarios(this); */
            prop.consultar();
            prop.setSize(670, 214);
            prop.setLocation(0,0);
            jPTablas.removeAll();
            jPTablas.add(prop);
            jPTablas.revalidate();
            jPTablas.repaint();
        }else{
            Autos autos = new Autos(this);
            autos.consultar(clientID);
            autos.setSize(670, 214);
            autos.setLocation(0,0);
            jPTablas2.removeAll();
            jPTablas2.add(autos);
            jPTablas2.revalidate();
            jPTablas2.repaint();
        }
    }
    
    public void actualizaVista(Principal principal){
        Propietarios propBack = new Propietarios(principal);
        propBack.consultar();
        propBack.setSize(670, 214);
        propBack.setLocation(0,0);
        jPTablas.removeAll();
        jPTablas.add(propBack);
        jPTablas.revalidate();
        jPTablas.repaint();
        
        jPTablas2.removeAll();
        jPTablas2.revalidate();
        jPTablas2.repaint();
        
        jlBack.setVisible(false);
        jLAddAutos.setVisible(false);
    }
    
    public void actualizaVistaAutos(Principal principal, int clientID){
            Autos autos = new Autos(principal);
            autos.consultar(clientID);
            autos.setSize(670, 214);
            autos.setLocation(0,0);
            jPTablas2.removeAll();
            jPTablas2.add(autos);
            jPTablas2.revalidate();
            jPTablas2.repaint();
    }
    
    public void buscar(String tipoBusqueda, String valorBusqueda,String filter){
        List<Integer> idCliente = new ArrayList<Integer>();
        if(tipoBusqueda.equals("Propietario")){
            if(!filter.equals("IdCliente")){
                prop.buscarPropietario(filter,valorBusqueda);
            }else{
                idCliente.add(Integer.parseInt(valorBusqueda));
                prop.buscarPropietarioID(idCliente);
            }
            prop.setSize(670, 214);
            prop.setLocation(0,0);
            jPTablas.removeAll();
            jPTablas.add(prop);
            jPTablas.revalidate();
            jPTablas.repaint();
            
            jPTablas2.removeAll();
            jPTablas2.revalidate();
            jPTablas2.repaint();
        }else if(tipoBusqueda.equals("Auto")){

            Autos autos = new Autos(this);
            idCliente = autos.buscarAuto(filter,valorBusqueda);
            autos.setSize(670, 214);
            autos.setLocation(0, 0);
            jPTablas2.removeAll();
            jPTablas2.add(autos);
            jPTablas2.revalidate();
            jPTablas2.repaint();
        
            prop.buscarPropietarioID(idCliente);
            prop.setSize(670, 214);
            prop.setLocation(0,0);
            jPTablas.removeAll();
            jPTablas.add(prop);
            jPTablas.revalidate();
            jPTablas.repaint();
        }
    }
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.ButtonGroup bgBuscarPor;
    private static javax.swing.ButtonGroup bgBusquedas;
    private javax.swing.JButton btnBuscar;
    public javax.swing.JLabel jLAddAutos;
    private javax.swing.JLabel jLAddPropietarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPTablas;
    public javax.swing.JPanel jPTablas2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel jlBack;
    private static javax.swing.JRadioButton rbApMaterno;
    private static javax.swing.JRadioButton rbApPaterno;
    private javax.swing.JRadioButton rbAuto;
    private static javax.swing.JRadioButton rbIdClienteAuto;
    private static javax.swing.JRadioButton rbIdClienteProp;
    private static javax.swing.JRadioButton rbNombre;
    private static javax.swing.JRadioButton rbPlacas;
    private javax.swing.JRadioButton rbPropietario;
    private static javax.swing.JRadioButton rbTelefono;
    private static javax.swing.JTextField tApMaterno;
    private static javax.swing.JTextField tApPaterno;
    private static javax.swing.JTextField tIdClienteAuto;
    private static javax.swing.JTextField tIdClienteProp;
    private static javax.swing.JTextField tNombre;
    private static javax.swing.JTextField tPlacas;
    private static javax.swing.JTextField tTelefono;
    // End of variables declaration//GEN-END:variables

}
